spring.application.name=SpringJwt
#spring.security.user.name=navin
#spring.security.user.password=telusko
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.properties.currentSchema=Sample_test
spring.datasource.username=postgres
spring.datasource.password=""
spring.jpa.hibernate.ddl-auto=create-drop
